// <auto-generated />
using System;
using KutuphaneOtomasyon.DatabaseContext2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211225141808_last")]
    partial class last
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Entitys.Models.Kitap", b =>
                {
                    b.Property<string>("BarkodNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAdi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KitapBaskiTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapSayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KitapTuru")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapYazari")
                        .HasColumnType("TEXT");

                    b.Property<bool>("alinabilirMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("BarkodNo");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("Entitys.Models.KutuphaneIslemleri", b =>
                {
                    b.Property<int>("IslemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KitapAlimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KitapIadeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciTC")
                        .HasColumnType("TEXT");

                    b.Property<double>("Ucret")
                        .HasColumnType("REAL");

                    b.HasKey("IslemID");

                    b.HasIndex("KitapID");

                    b.HasIndex("OgrenciTC");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("Entitys.Models.Ogrenci", b =>
                {
                    b.Property<string>("OgrenciTc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciBorc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciOkul")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciSoyadi")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciTc");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Entitys.Models.KutuphaneIslemleri", b =>
                {
                    b.HasOne("Entitys.Models.Kitap", "Kitap")
                        .WithMany("KitapIslemler")
                        .HasForeignKey("KitapID");

                    b.HasOne("Entitys.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciIslemler")
                        .HasForeignKey("OgrenciTC");

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Entitys.Models.Kitap", b =>
                {
                    b.Navigation("KitapIslemler");
                });

            modelBuilder.Entity("Entitys.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciIslemler");
                });
#pragma warning restore 612, 618
        }
    }
}
